workspace: 
  src: 'FUAM Master DEV'
  trg: 'FUAM Master TEST'
connections:
  pbi_connection :
    src: fuam pbi-service-api admin
    trg: fuam pbi-service-api admin
  fabric_connection: 
    src: fuam fabric-service-api admin
    trg: fuam fabric-service-api admin

items:
  - FUAM_Lakehouse.Lakehouse
  - FUAM_Config_Lakehouse.Lakehouse
  - FUAM_Staging_Lakehouse.Lakehouse

  - Generate_Calendar_Table.Notebook
  - Init_FUAM_Lakehouse_Tables.Notebook

  - 01_Transfer_Active_Items_Unit.Notebook
  - Load_Items_E2E.DataPipeline

  - 02_Transfer_Activities_Unit.Notebook
  - 03_Aggregate_Activities_Unit.Notebook
  - Load_Activities_E2E.DataPipeline

  - 01_Transfer_Capacities_Unit.Notebook
  - Load_Capacities_E2E.DataPipeline

  - 01_Transfer_Capacity_Refreshables_Unit.Notebook
  - Load_Capacity_Refreshables_E2E.DataPipeline

  - 02_Transfer_Workspaces_Unit.Notebook
  - Load_PBI_Workspaces_E2E.DataPipeline

  - 01_Transfer_Incremental_Inventory_Unit.Notebook
  - Load_Inventory_E2E.DataPipeline

  - 01_Transfer_Delegated_Tenant_Settings_Overrides_Unit.Notebook
  - 01_Transfer_Tenant_Admin_Settings_Unit.Notebook
  - Load_Tenant_Settings_E2E.DataPipeline
  - Load_Delegated_Tenant_Settings_Overrides_E2E.DataPipeline

  - 01_Transfer_Git_Connections_Unit.Notebook
  - Load_Git_Connections_E2E.DataPipeline

  - FUAM_Backup_Lakehouse.Lakehouse
  - 01_FUAM_Lakehouse_Backup.Notebook
  - 02_FUAM_Lakehouse_Optimization.Notebook
  - Maintenance_for_FUAM.DataPipeline


  - 01_Transfer_CapacityMetricData_Timepoints_Unit.Notebook
  - 02_Transfer_CapacityMetricData_ItemKind_Unit.Notebook
  - 03_Transfer_CapacityMetricData_ItemOperation_Unit.Notebook
  - Load_Capacity_Metrics_E2E.DataPipeline

  - Load_FUAM_Data_E2E.DataPipeline

  - FUAM_Item_SM.SemanticModel
  - FUAM_Item_Analyzer_Report.Report

  - FUAM_Core_SM.SemanticModel
  - FUAM_Core_Report.Report

  - FUAM_Semantic_Model_Meta_Data_Analyzer_SM.SemanticModel
  - FUAM_Semantic_Model_Meta_Data_Analyzer_Report.Report

  - FUAM_SQL_Endpoint_Analyzer_SM.SemanticModel
  - FUAM_SQL_Endpoint_Analyzer_Report.Report

  - FUAM_Gateway_Monitoring_From_Files_SM.SemanticModel
  - FUAM_Gateway_Monitoring_From_Files_Report.Report

fuam_lakehouse_semantic_models:
  - FUAM_Core_SM.SemanticModel
  - FUAM_Item_SM.SemanticModel
